# Description
#   A Drake Quote generator for Hubots.
#
# Configuration:
#   None
#
# Commands:
#   hubot drizzy quote me - displays a random quote from drake
#

quotes = [
  "When you call too much, then I call less. You would always complain about my small texts, but what you call conversation, I call stress.",
  "You don't love me, you just say that s*** to get to me.",
  "We all have our nights though, don't be so ashamed. I've had mine, you've had yours, we both know.",
  "Never thoughts of suicide, I'm too alive. But I still treat it like it's do or die.",
  "I gotta feel alive, even if it kills me. Promise to always give you me, the real me.",
  "F*** with me, I'll buy the shots. Live a little, cause niggas die a lot.",
  "I hate getting messages from you, it's like you know the perfect s*** to say. F***s up my whole day, thought all these feelings went away.",
  "Watch me, going out of the way, when I should've went home. Only time of the day I get to spend on my own.",
  "Makin' major changes to the life I'm livin'. I had no choice, I had to prove I made the right decision.",
  "Can't deny that I want you, but I'll lie if I have to.",
  "No new niggas, nigga we don't feel that. F*** a fake friend, where ya real friends at?",
  "I say f*** ya, less I'm with ya. If I take you out of the picture, I know real niggas won't miss ya, no lie.",
  "I finally get a moment to myself, I would realize you were everything I'm missing, and you'll tell me you're in love with someone else.",
  "I just need some closure. Ain't no turnin' back for me, I'm in it till it's over.",
  "I was stayin' home when they was havin' fun, so please don't be surprised when they announce that I won.",
  "Feelin' good, livin' better. I think maybe I was numb to it last year, but you know I feel it now more than ever.",
  "You let me go, little did you know, I could've made it all on my own.",
  "I got my eyes on you, you're everything that I see. I want your hot love and emotion endlessly.",
  "Accept yourself. You don't have to prove s*** to no one except yourself.",
  "Don't get impatient when it takes too long, and drink it all even when it tastes too strong.",
  "All so convinced that you're following your heart, cause your mind don't control what it does sometimes.",
  "They say real girls ain't never perfect, perfect girls ain't real.",
  "Ain't no wishing over on this side. Y'all don't f*** with us then we don't f*** with y'all, it's no different over on this side.",
  "We walk the same path, but got on different shoes. Live in the same building, but we got different views.",
  "I'd rather be with you, but you are not around. So I'ma call somebody up and see if they'd be down, cause I hate sleeping alone.",
  "You were the one. You've been the one from the moment I seen ya.",
  "My family gets all of my loyalty, all of my patience. My life for your life, man I wouldn't trade it.",
  "Don't ever forget the moment you began to doubt, transitioning from fitting in to standing out.",
  "I guess that's how it goes. They hear about your cons, but focus on your pros, and love you for who you are from the bottom of their soul.",
  "Make sure you don't fall in love, cause I don't have the time for that.",
  "Too many times I've been wrong, I guess being right takes too long.",
  "Isn't it amazing how you talk all this s*** and we still lack communication.",
  "May your neighbors respect you, trouble neglect you. Angels protect you, and heaven accept you.",
  "How I put it on you, crazy. That's when you start to laugh, saying I just want what I can't have.",
  "I'm still fly, I'm sky high, and I dare anybody to try and cut my wings.",
  "You love me and I love you, and your heart hurts, mine does too. And it's just words and they cut deep but it's our world, it's just us two.",
  "My life is moving fast, the time will often past. And something will remind me, I can't put this behind me.",
  "I'm just doin' me and you could never understand it.",
  "We sure make it feel like we're together, cause we're scared to see each other with somebody else.",
  "I was a cold dude, I'm gettin' back to my ways.",
  "I hate the s*** you do, but I still text you back, say I miss you too." ,
  "The weekend's here, started it right, even if you only get part of it right.",
  "If you end up needin some extra help then I can help.You know, back on ya feet and s***.Tryna get my karma up, f*** the guilty & greedy s***",
  "Holla if you got me and f*** you if you had me.",
  "Young, dumb, lookin' in the mirror tryin' to figure out who I'm gonna be this year.",
  "All them boys in my will, all them boys is my Wills. Anything happen to pop and I got you like Uncle Phil.",
  "You got your resolutions, we just got reservations.",
  "Feelin' good, livin' better. But it's evident that nothing can prepare us for certain moments that you just gotta cherish.",
  "Got everything I'm asking for but you.",
  "I'm slowly running out of all the time that I invested, making all the same mistakes and I'm just trying to correct it.",
  "It's such a small place, not much to do but talk and listen. The men are jealous and the women all in competition.",
  "Next time I stand tall, I wanna be standing for you. And next time I spend I want it all to be for you.",
  "This here is something personal, highly doubt this feeling is reversible. Knowledge is pain and that's why it hurts to know.",
  "I'm lucky that you picked up, lucky that you stayed on. I need someone to put this weight on.",
  "I've been avoiding commitment, that's why I'm in this position. I'm scared to let somebody in on this.",
  "I'm thinkin' about my goals, and how we used to say a goal is just a dream with a deadline.",
  "I've asked about you and they told me things. But my mind didn't change, I still feel the same.",
  "Sweat pants, hair tied, chillin' with no makeup on. That's when you're the prettiest, I hope that you don't take it wrong.",
  "I'm honest, I make mistakes, I'd be the second to admit it." ,
  "I'm really tryna make it more than what it is, cause everybody dies but not everybody lives.",
  "The good ones go, if you wait too long. So you should go, before you stay too long.",
  "That's why I pick and choose. I don't get s*** confused. I got a small circle, I'm not with different crews.",
  "Make it sooner than later, we won't be here forever. And I realize I waited too long, but please don't move on. You dont need no one else.",
  "People around you should really have nothing to say. Me, I'm just proud of the fact that you've done it your way.",
  "I try to tell them don't judge me because you heard stuff.",
  "I really hate to say I told you so. So I bite my tongue but you know, you know.",
  "You know it's real when you are who you think you are." ,
  "Now you're trying to find somebody to replace what I gave to you. It's a shame you didn't keep it.",
  "I'm trying to let go of the past. Should we make this one a double? You ain't even gotta ask.",
  "I be hearin' the s*** that you say through the grapevine, but jealousy is just love and hate at the same time.",
  "I forgot about you last night, for the first time in a long time I did.",
  "All in all I learned a lesson from it though, you never see it coming you just get to see it go.",
  "I like a woman with a future and a past. A little attitude problem all good, it'll make the s*** last.",
  "Somewhere between I want it and I got it." ,
  "Just lie to my ears. Tell me it feel the same, that's all I've been dying to hear.",
  "You say that you're over me, you always end up under me. You know how it goes, don't be crazy, don't play dumb with me.",
  "Heard once that in dire times when you need a sign, that's when they appear." ,
  "Live for today, plan for tomorrow, party tonight.",
  "Guess you lose some and win some. As long as the outcome is income, you know I want it all and then some.",
  "She's the reason it happened, but she's overreacting, and it's all because she don't want things to change.",
  "I should let you know ahead, I'm coming back on my worst behavior." ,
  "I love myself cause I swear their life is just not as fun.",
  "I don't really give a f***, and my excuse is that I'm young.",
  "I'm still in love, cause when it's that real, it's when it doesn't fade.",
  "My only wish is I die real. Cause that truth hurts, and those lies heal.",
  "Looking back on it, at least my pride is in tact. Cause we said no strings attached, and I still got tied up in that.",
  "Take all my memories with you and just erase it for me, you can never reminisce when you forget it all.",
  "Overly focused, it's far from the time to rest now." ,
  "Jealousy in the air tonight, I could tell. I will never understand that, but oh well." ,
  "She used to say, 'you can be whoever you want, even yourself.' I show up knowin' exactly who I was and never leave as myself." ,
  "We had the type of nights where morning comes too soon, and nothing was the same." ,
  "I just been plottin' on the low. Schemin' on the low. The furthest thing from perfect, like everyone I know." ,
  "Actin like oh well, this is life, I guess. Nah, f*** that s***. Listen man, you can still do what you wanna do, you gotta trust that s***.",
  "Same city, same friends if you're looking for me." ,
  "Tables turn, bridges burn, you live and learn." ,
  "All my young boys ‘round me sayin', 'get money and f*** these hoes.' Where we learn these values? I do not know what to tell you.",
  "Talkin' that s*** with your back to me, just know it always get back to me." ,
  "Wish you would learn to love people and use things, and not the other way around." ,
  "I felt like we had it all planned out, I guess I f***ed up the vision. Learning the true consequences of my selfish decisions." ,
  "the album is comin' tomorrow just wait on it.",
  "You ain't the only one that's tryna be the only one." ,
  "It's been one of those days you try and forget about, take a shot and let it out." ,
  "This the s*** that I live for, with the people I die for." ,
  "See the difference with me, I don't forget the past. And you gave me nothing, so I'ma give you nothing right back.",
  "Should I listen to everybody or myself? Cause myself just told myself, 'you the motherf***in' man, you don't need no help.'",
  "The girl that I want to save is like a danger to my health. Try being with somebody that want to be somebody else.",
  "Bullets do not choose a victim. It is the shooter that picks ‘em.",
  "You know it's real when your latest nights are your greatest nights. The sun is up when you get home, that's just a way of life.",
  "Sinatra lifestyle, I'm just bein' frank with ya.",
  "Lookin' for the right way to do the wrong things.",
  "I spend money because spending time is hopeless, and know I pop bottles cause I bottle my emotions. At least I put it all in the open.",
  "I'ma worry about me, give a f*** about you.",
  "Everything's adding up, you've been through hell and back, that's why you're bad as f***, and you know you are.",
  "Careful what you wish for, you just might get it all.",
  "I could tell a lie if you askin' me my whereabouts, but I might talk that real if you ask me what I care about.",
  "A lot of people sayin' f*** me, problem is they be tellin' everybody but me.",
  "She said kiss me like you miss me, f*** me like you hate me. And when you're f***in' someone else, just f*** her like she ain't me.",
  "You got the resolutions, we just got reservations.",
  "Live fast, die young, never take it slow.",
  "You think you got to me, I can just read your mind. You think I'm so caught up in where I am right now, but believe I remember it all.",
  "I still got it for ya, and even though we let it go, it's better that you know.",
  "I'm good, I don't need no help. Cause I'm better off by myself then to start over with somebody else.",
  "Started not to give a f*** and stopped fearin' the consequence.",
  "You mad cause nobody ever did it like me.",
  "The good ones go, if you wait too long.",
  "Never forgetting from where I came, and no matter where I'm headed, I promise to stay the same.",
  "I want things to go my way, but as of late a lot of s*** been goin' sideways.",
  "Talking to myself but I never listen. Cause man it's been awhile, and I swear that this one's different.",
  "It's funny when you coming in first but you hope that you're last, you just hope that it last.",
  "Only thing you got is some years on me. Man, f*** you and your time difference.",
  "I'd really love to be the one you took a step with, so trust me when I tell you it'd be worth the effort.",
  "To have known me would mean that there's a new me. And if you think I changed in the slightest, could've fooled me.",
  "Say you'll be mine, say we'll be fine, say we'll be together.",
  "You probably think it's too far to even have to care, well take a look at where you live, what if it happened there?",
  "I learned working with the negatives could make for better pictures.",
  "I'm in the world where things are taken, never given. How long they choose to love you will never be your decision.",
  "Guess you lose some and win some. Long as the outcome is income, you know I want it all and then some.",
  "I'ma sip until I feel it, I'ma smoke it till it's done. I don't really give a f***, and my excuse is that I'm young.",
  "I'm tryna do better than good enough.",
  "When all is said and done, more is always said than done.",
  "I hate getting messages from you, especially when you say you should've stayed. F***s up my whole day, thought all these feelings went away.",
  "If it's comin' from a nigga I don't know, then I don't trust it. If you comin' for my head, then motherf***er get to bustin'.",
  "They say if you get her, you could understand her better. And she known to be a cheater, but that's only if you let her.",
  "Damn, what happened to us? Life can always change, you have to adjust.",
  "Mind in one place, heart in another.",
  "I can tell certain people don't like me no more, new s*** don't excite me no more, guess they don't really make ‘em like me no more.",
  "Just as I predicted, here we go again. They always say the hottest love has the coldest end.",
  "Don't ask permission, just ask forgiveness.",
  "You know life is what we make it, and a chance is like a picture, it'd be nice if you just take it.",
  "These haters pretendin' that it's all good. Say that s*** in person man, I wish y'all would.",
  "Is this even still a discussion? Don't you ever wake up disgusted? Every million I gain an enemy or a cousin.",
  "Call me crazy, s*** at least you callin'. Feels better when you let it out, don't it?",
  "I was curious and I'll never forget it baby, what an experience. You could've been the one, but it wasn't that serious.",
  "I can tell that you've been crying all night, drinking all summer. Praying for your happiness, hope that you recover.",
  "This life is something I would die for. Octobers Own, but it's lookin' like July 4th.",
  "Damn, tell me what I'm gon' do, since everything I'm trying to forget is all true.",
  "We just kill the summer every single time it come around. Never chase hoes, but we do be laughin' at the niggas tryna run 'em down.",
  "I'm more than just a number, I doubt you'll find another. So every single summer, I'll be the one that you remember.",
  "I know you waiting, waiting on a good thing. When the time's right, you should let me get to know you.",
  "I think I have a chance at love but knowing me I'll miss it, cause me dedicating my time just isn't realistic.",
  "Shawty wanna tell me secrets bout a rap nigga. I tell that bitch it's more attractive when you hold it down.",
  "I never really had no one like you man, this all new s***. Made the world I know bigger, changed the way that I viewed it.",
  "I'm about bein' single, seein' double, makin' triple.",
  "Hennessy and enemies is one hell of a mixture.",
  "Worryin' bout your followers, you need to get your dollars up.",
  "Me falling and landing in love, I don't think should happen. Because everything's easier to get into than get out of.",
  "You don't do it for the men, men never notice. You just do it for yourself, you the f***in' coldest.",
  "My dreams are who I'm racin' with, but you can see I'm pacin' it, so that I'm always chasin' it.",
  "If amazing was a young bitch, I'd be going to jail cause I be f***in' amazing.",
  "You lookin' bad, girl for goodness sakes. You with all those curves, and me without no brakes.",
  "Tell me how the f*** we supposed to stay friends, when you got a bunch of feelings that you don't show.",
  "Daydream at nighttime, I think too much. Then I hit the nightclub till it's daytime and I drink too much.",
  "Tell on me, I don't mind. Cause if they ask me about it, I won't lie. I'll admit that I'm yours, I don't really care who knows it.",
  "They told me s*** would change, but I don't really see no change in us.",
  "Women need attention therefore women will complain. Develop hatred for men and say that you're the one to blame.",
  "It's crazy all the emotions forgot in a year.",
  "I'm urgin all daughters to kiss they mothers,with those lips that all that lipstick covers. You're never too grown up to miss and hug her.",
  "Make the most out of tonight and worry 'bout it all tomorrow."
]

module.exports = (robot) ->
  robot.respond /drizzy quote me\b/i, (msg) ->
      msg.send msg.random quotes

  robot.respond /drake quote me\b/i, (msg) ->
      msg.send msg.random quotes

  robot.respond /drizzy version\b/i, (msg) ->
      msg.send require('../package').version

